### ISSUE TITLE
Unable to reproduce Reacher ptf-ppo results.

### ISSUE THREAD

**Issue by NagisaZj** [tianpeiyang/PTF_code#7]
Hi, I am trying to reproduce ptf-ppo on the Reacher domain. I run the commands provided in README.md:
`
CUDA_VISIBLE_DEVICES=4  python main.py -a ptf_ppo -c ptf_ppo_conf -g reacher -d reacher_conf -n 10000 -e 1000 -s 2 -o adam n_layer_a_1=256 n_layer_c_1=256 learning_rate_a=3e-4 learning_rate_c=3e-4 learning_rate_o=1e-3 learning_rate_t=1e-3 e_greedy=0.95 e_greedy_increment=1e-2 replace_target_iter=1000 reward_decay=0.99 option_model_path=['source_policies/reacher/t1/model','source_policies/reacher/t2/model','source_policies/reacher/t3/model','source_policies/reacher/t4/model'] learning_step=10000 save_per_episodes=1000 task=hard c1=0.001 source_policy=a3c clip_value=10 batch_size=300 option_batch_size=16 reward_normalize=True done_reward=10 option_layer_1=20`

According to the results in the paper, it should eventually get return of about 60, but I am not geting the expected outcome. It only gets a final return of about 15, as shown in the attached figure (the blue line was ran for 10e4 episodes). I have not modified any code, and it would be great if you look into it.

![image](https://user-images.githubusercontent.com/26165156/160332351-c67e317c-de38-43d1-9f2a-f44e73312e63.png)

**Comment by tianpeiyang** [comment]
Hi, as we mentioned in the paper, we design different tasks with different locations to reach, so the 'reacher.py' file in dm_control has been modified. We have uploaded the modified 'reacher.py' in \games\. We also re-run the experiments on Reacher, the results are as follows (due to the limit of resources, results are averaged on 3 seeds):
![results](https://user-images.githubusercontent.com/4443373/160759133-b8820ef8-1391-44c6-9bf5-e7ad78457def.png)

**Comment by NagisaZj** [comment]
Thanks for the reply! I will try again with the latest code : )

It seems that in the latest code Reacher is not registered.

```
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    runGames(args)
  File "main.py", line 177, in runGames
    env = env_REGISTRY[args['game']](args)
KeyError: 'reacher'
```

I looked into games/__init__.py, line 10 is commented. Maybe you forgot to register Reacher.

**Comment by tianpeiyang** [comment]
Yep, just uncomment that line.

**Comment by NagisaZj** [comment]
Hi, unfortunately I am still not getting the expected results. I ran two ptf-ppo (orange and blue in the attached figure) and one ptf-a3c (red) and they are only getting an average return about 2. I've replaced the reachers.py in dm_control, and here's the command I ran ptf-ppo:

`CUDA_VISIBLE_DEVICES=4 python main.py -a ptf_ppo -c ptf_ppo_conf -g reacher -d reacher_conf -n 10000 -e 1000 -s 2 -o adam n_layer_a_1=256 n_layer_c_1=256 learning_rate_a=3e-4 learning_rate_c=3e-4 learning_rate_o=1e-3 learning_rate_t=1e-3 e_greedy=0.95 e_greedy_increment=1e-2 replace_target_iter=1000 reward_decay=0.99 option_model_path=['source_policies/reacher/t1/model','source_policies/reacher/t2/model','source_policies/reacher/t3/model','source_policies/reacher/t4/model'] learning_step=10000 save_per_episodes=1000 task=hard c1=0.001 source_policy=a3c clip_value=10 batch_size=300 option_batch_size=16 reward_normalize=True done_reward=10 option_layer_1=20`
![image](https://user-images.githubusercontent.com/26165156/161213841-8dd95469-9231-431c-a39a-a312767451fe.png)

Here's my pip list:

```
Package                           Version       Location
--------------------------------- ------------- -------------------------------
absl-py                           1.0.0
aiohttp                           3.8.1
aiohttp-cors                      0.7.0
aioredis                          2.0.1
aiosignal                         1.2.0
akro                              0.0.8
alabaster                         0.7.12
antlr4-python3-runtime            4.8
anyio                             3.5.0
appdirs                           1.4.4
argcomplete                       1.12.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
astor                             0.8.1
astunparse                        1.6.3
async-generator                   1.10
async-timeout                     4.0.2
asynctest                         0.13.0
attrs                             21.2.0
Babel                             2.9.1
backcall                          0.2.0
beautifulsoup4                    4.10.0
black                             20.8b1
bleach                            4.1.0
blessings                         1.7
Brotli                            1.0.9
cached-property                   1.5.2
cachetools                        4.2.4
certifi                           2021.5.30
cffi                              1.15.0
cfgv                              3.3.1
charset-normalizer                2.0.10
clang                             5.0
click                             8.0.3
cloudpickle                       2.0.0
cma                               2.7.0
colorama                          0.4.4
colorful                          0.5.4
colorlog                          4.8.0
contextvars                       2.4
cycler                            0.11.0
Cython                            0.29.27
dataclasses                       0.7
decorator                         4.4.2
defusedxml                        0.7.1
Deprecated                        1.2.13
distlib                           0.3.4
dm-control                        0.0.364896371
dm-control2gym                    0.0.2
dm-env                            1.5
dm-tree                           0.1.6
docutils                          0.18.1
dowel                             0.0.3
entrypoints                       0.3
execnet                           1.9.0
fasteners                         0.17.3
filelock                          3.4.0
flake8                            3.8.4
flake8-bugbear                    20.11.1
flake8-comprehensions             3.3.1
flake8-docstrings                 1.5.0
Flask                             2.0.2
Flask-Compress                    1.10.1
flatbuffers                       1.12
frozenlist                        1.2.0
future                            0.18.2
gast                              0.3.2
glfw                              2.5.0
google                            3.0.0
google-api-core                   2.4.0
google-auth                       1.35.0
google-auth-oauthlib              0.4.6
google-pasta                      0.2.0
googleapis-common-protos          1.54.0
gpustat                           0.6.0
grpcio                            1.43.0
gym                               0.10.9
h5py                              3.1.0
hiplot                            0.1.22
hydra-core                        1.0.5
hydra-submitit-launcher           1.0.1
identify                          2.4.4
idna                              3.3
idna-ssl                          1.1.0
imageio                           2.9.0
imageio-ffmpeg                    0.4.3
imagesize                         1.3.0
immutables                        0.16
importlib-metadata                4.8.3
importlib-resources               5.4.0
incremental                       21.3.0
iniconfig                         1.1.1
ipykernel                         5.5.6
ipython                           7.16.3
ipython-genutils                  0.2.0
ipywidgets                        7.6.5
isort                             5.7.0
itsdangerous                      2.0.1
jedi                              0.17.2
Jinja2                            3.0.3
json5                             0.9.6
jsonschema                        3.2.0
jupyter                           1.0.0
jupyter-client                    7.1.2
jupyter-console                   6.4.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.9.1
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.13.1
jupyterlab                        3.0.3
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.10.3
jupyterlab-widgets                1.0.2
keras                             2.6.0
Keras-Applications                1.0.8
Keras-Preprocessing               1.1.2
kiwisolver                        1.3.1
labmaze                           1.0.5
latexcodec                        2.0.1
lxml                              4.7.1
Markdown                          3.3.6
MarkupSafe                        2.0.1
matplotlib                        3.3.3
mccabe                            0.6.1
metaworld                         0.0.0         /data2/zj/NewMTRL/src/metaworld
mistune                           0.8.4
mkl-fft                           1.3.0
mkl-random                        1.1.1
mkl-service                       2.3.0
mllogger                          0.7
msgpack                           1.0.3
mtenv                             1.0           /data2/zj/NewMTRL/src/mtenv
mujoco-py                         2.0.2.13
multidict                         5.2.0
mypy                              0.790
mypy-extensions                   0.4.3
nbclassic                         0.3.5
nbclient                          0.5.9
nbconvert                         6.0.7
nbformat                          5.1.3
nest-asyncio                      1.5.4
networkx                          2.5.1
nodeenv                           1.6.0
notebook                          6.4.8
nox                               2020.12.31
numpy                             1.19.5
nvidia-ml-py3                     7.352.0
oauthlib                          3.2.0
omegaconf                         2.0.6
opencensus                        0.8.0
opencensus-context                0.1.2
opencv-python                     4.5.1.48
opt-einsum                        3.3.0
packaging                         21.3
pandas                            1.1.5
pandocfilters                     1.5.0
parso                             0.7.1
pathspec                          0.9.0
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            7.1.0
pip                               21.2.2
platformdirs                      2.4.0
pluggy                            0.13.1
pockets                           0.9.1
pre-commit                        2.9.3
prometheus-client                 0.13.1
prompt-toolkit                    3.0.26
protobuf                          3.19.3
psutil                            5.8.0
ptyprocess                        0.7.0
py                                1.11.0
py-spy                            0.3.11
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pybtex                            0.24.0
pybtex-docutils                   1.0.1
pycodestyle                       2.6.0
pycparser                         2.21
pydocstyle                        6.1.1
pyflakes                          2.2.0
pygame                            1.9.4
pyglet                            1.5.21
Pygments                          2.11.2
pymongo                           3.11.2
PyOpenGL                          3.1.5
pyparsing                         3.0.7
pyrsistent                        0.18.0
pytest                            6.2.1
pytest-forked                     1.4.0
pytest-xdist                      2.2.0
python-dateutil                   2.8.2
pytz                              2021.3
PyWavelets                        1.1.1
PyYAML                            5.4.1
pyzmq                             22.3.0
qtconsole                         5.2.2
QtPy                              2.0.0
ray                               1.0.1.post1
redis                             3.4.1
regex                             2022.1.18
requests                          2.27.1
requests-oauthlib                 1.3.1
rsa                               4.8
scikit-image                      0.17.2
scipy                             1.5.4
Send2Trash                        1.8.0
setproctitle                      1.2.2
setuptools                        51.1.1
six                               1.16.0
sniffio                           1.2.0
snowballstemmer                   2.2.0
soupsieve                         2.3.1
Sphinx                            3.4.3
sphinx-autodoc-annotation         1.0.post1
sphinx-copybutton                 0.3.1
sphinx-rtd-theme                  0.5.1
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-bibtex              2.1.3
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-napoleon            0.7
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.5
submitit                          1.4.1
tabulate                          0.8.9
tensorboard                       1.14.0
tensorboard-logger                0.1.0
tensorboardX                      2.4.1
tensorflow                        1.14.0
tensorflow-estimator              1.14.0
tensorflow-probability            0.15.0
termcolor                         1.1.0
terminado                         0.12.1
testpath                          0.5.0
tifffile                          2020.9.3
toml                              0.10.2
torch                             1.7.1+cu110
torchvision                       0.8.2+cu110
tornado                           6.1
towncrier                         19.2.0
tqdm                              4.62.3
traitlets                         4.3.3
typed-ast                         1.4.3
typing-extensions                 3.7.4.3
urllib3                           1.26.8
virtualenv                        20.13.0
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.2.3
Werkzeug                          2.0.2
wheel                             0.37.1
widgetsnbextension                3.5.2
wrapt                             1.13.3
yamllint                          1.25.0
yarl                              1.7.2
zipp                              3.6.0
```

**Comment by tianpeiyang** [comment]
Sorry I just saw this, Github did not send email to notify me.
Did you replace the 'reacher.py' file in your 'conda env'/Lib/site-packages/dm_control/suite/reacher.py with the game/reacher.py? I used the same command as yours, it shouldn't get such results.

I have checked the pip package versions, all others are okay, only the dm_control version is 0.0.0. However, I checked currently dm-control does not support 0.0.0

This is what I test it again:

![image](https://user-images.githubusercontent.com/4443373/171097120-576e99aa-4489-49f2-945c-df77afdcdc57.png)

If you do change the reacher.py file in your conda env and still cannot reproduce it, I will send you the dm-control 0.0.0 to you, please send me your email, thanks.

**Comment by NagisaZj** [comment]
Yes I am pretty sure I replaced reacher.py. My email is jin-zhan20@mails.tsinghua.edu.cn

**Comment by tianpeiyang** [comment]
Sent it to you.

**Comment by NagisaZj** [comment]
It works well with your dm_control. That's a little wired and surprising. Maybe you can include your dm_control in this repo.
